# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Apartment.create(number: 101, owner: 'Juan Velasquez' ,rent: 205000)
Apartment.create(number: 102, owner: 'Miguel Pelaz' ,rent: 244000)
Apartment.create(number: 103, owner: 'Aida Jaimes' ,rent: 216000)
Apartment.create(number: 104, owner: 'Paola Patiño' ,rent: 111000)
Apartment.create(number: 201, owner: 'Nancy Avilan' ,rent: 142000)
Apartment.create(number: 202, owner: 'German Avilan' ,rent: 135000)
Apartment.create(number: 301, owner: 'Luisa Tobar' ,rent: 153000)
Apartment.create(number: 302, owner: 'Alberto Acevedo' ,rent: 128000)
Apartment.create(number: 303, owner: 'Pedro Betancourt' ,rent: 224000)
Apartment.create(number: 304, owner: 'Gerardo Salcedo' ,rent: 226000)
Apartment.create(number: 305, owner: 'Catalina Peralta' ,rent: 266000)
Apartment.create(number: 401, owner: 'Maria C. Fontecha' ,rent: 142000)
Apartment.create(number: 501, owner: 'Dario Villamizar' ,rent: 252000)
Apartment.create(number: 502, owner: 'Isabel Angel' ,rent: 166000)
Apartment.create(number: 503, owner: 'Claudia Bohorquez' ,rent: 241000)
Tenant.create(name: 'Emilce Suarez' ,email: 'prueba@gmail.com',apartment_id:1, move_in:2018, move_out:2018)
Tenant.create(name: 'Adriana Bernal' ,email: 'prueba@gmail.com',apartment_id:2, move_in:2018, move_out:2018)
Tenant.create(name: 'Carolina Bejarano' ,email: 'prueba@gmail.com',apartment_id:3, move_in:2018, move_out:2018)
Tenant.create(name: 'Paola Patiño' ,email: 'prueba@gmail.com',apartment_id:4, move_in:2018, move_out:2018)
Tenant.create(name: 'Nancy Avilan' ,email: 'prueba@gmail.com',apartment_id:5, move_in:2018, move_out:2018)
Tenant.create(name: 'Catalina Bautista' ,email: 'prueba@gmail.com',apartment_id:6, move_in:2018, move_out:2018)
Tenant.create(name: 'Luisa Tobar' ,email: 'prueba@gmail.com',apartment_id:7, move_in:2018, move_out:2018)
Tenant.create(name: 'Andres Chavez' ,email: 'prueba@gmail.com',apartment_id:8, move_in:2018, move_out:2018)
Tenant.create(name: 'Pedro Betancourt' ,email: 'prueba@gmail.com',apartment_id:9, move_in:2018, move_out:2018)
Tenant.create(name: 'Gerardo Salcedo' ,email: 'prueba@gmail.com',apartment_id:10, move_in:2018, move_out:2018)
Tenant.create(name: 'Roberto Peralta' ,email: 'prueba@gmail.com',apartment_id:11, move_in:2018, move_out:2018)
Tenant.create(name: 'Daniel Guyumus' ,email: 'prueba@gmail.com',apartment_id:12, move_in:2018, move_out:2018)
Tenant.create(name: 'Dario Villamizar' ,email: 'prueba@gmail.com',apartment_id:13, move_in:2018, move_out:2018)
Tenant.create(name: 'Isabel Angel' ,email: 'prueba@gmail.com',apartment_id:14, move_in:2018, move_out:2018)
Tenant.create(name: 'Claudia Bohorquez' ,email: 'prueba@gmail.com',apartment_id:15, move_in:2018, move_out:2018)

